version: "3.8"

services:
  movies:
    build:
      context: .
      target: ${ENVIRONMENT}
    platform: linux/amd64
    environment:
      - SECRET_KEY=my-secret-key
      - DEBUG=1
      - ENVIRONMENT=development
      - POSTGRES_HOST="movie-db"
      - POSTGRES_USER="movies"
      - POSTGRES_PASSWORD="movies"
      - POSTGRES_DB="movies"

    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/"
    depends_on:
      - movies-db

  movies-db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST=movies-db
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies
    ports:
      - "5432:5432"

volumes:
  postgres_data:
